/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    sites: Site;
    pages: Page;
    services: Service;
    bookings: Booking;
    media: Media;
    clients: Client;
    templates: Template;
    sectors: Sector;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    sites: {
      sitePages: 'pages';
      siteServices: 'services';
      siteBookings: 'bookings';
    };
  };
  collectionsSelect: {
    sites: SitesSelect<false> | SitesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    sectors: SectorsSelect<false> | SectorsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Ouvrez un site → les pages viennent du modèle choisi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  name: string;
  /**
   * Obligatoire à la création. Enregistrez le site → Accueil, Bouquets, Contact, etc. sont assignés d’un coup.
   */
  template?: (number | null) | Template;
  /**
   * Ex. fleuriste-dupont → /sites/fleuriste-dupont
   */
  slug: string;
  /**
   * Publié = site en ligne + pages en brouillon publiées automatiquement.
   */
  status: 'draft' | 'published' | 'archived';
  client?: (number | null) | Client;
  sector?: (number | null) | Sector;
  /**
   * Liste des pages du modèle rattachées à ce site. Édition uniquement.
   */
  sitePages?: {
    docs?: (number | Page)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Bouquets et articles de la boutique.
   */
  siteServices?: {
    docs?: (number | Service)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Réservations et messages reçus depuis le site.
   */
  siteBookings?: {
    docs?: (number | Booking)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  theme?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    accentColor?: string | null;
    fontHeading?: string | null;
    fontBody?: string | null;
    borderRadius?: ('small' | 'medium' | 'large') | null;
  };
  contact?: {
    phone?: string | null;
    email?: string | null;
    address?: string | null;
    hours?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  socialLinks?:
    | {
        platform: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  domain?: string | null;
  subdomain?: string | null;
  useCustomDomain?: boolean | null;
  seo?: {
    defaultTitle?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
  };
  publishedAt?: string | null;
  clonedFromTemplateAt?: string | null;
  templateVersion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Modèles utilisés pour créer automatiquement pages et produits de démo.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: number;
  name: string;
  slug: string;
  sector?: (number | null) | Sector;
  description?: string | null;
  previewImage?: (number | null) | Media;
  defaultTheme?: {
    primaryColor?: string | null;
    secondaryColor?: string | null;
    accentColor?: string | null;
    fontHeading?: string | null;
    fontBody?: string | null;
    borderRadius?: ('small' | 'medium' | 'large') | null;
  };
  defaultPages?:
    | {
        title: string;
        slug: string;
        eyebrow?: string | null;
        excerpt?: string | null;
        isHomepage?: boolean | null;
        blocksJson?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        seo?: {
          title?: string | null;
          description?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  defaultServices?:
    | {
        title: string;
        slug: string;
        category?: string | null;
        badge?: string | null;
        deliveryLabel?: string | null;
        shortDescription?: string | null;
        imageUrl?: string | null;
        featured?: boolean | null;
        order?: number | null;
        price?: {
          from?: number | null;
          currency?: string | null;
          onRequest?: boolean | null;
        };
        id?: string | null;
      }[]
    | null;
  defaultBlocks?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors".
 */
export interface Sector {
  id: number;
  name: string;
  slug: string;
  icon?: (number | null) | Media;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  scope?: ('global' | 'template' | 'site') | null;
  site?: (number | null) | Site;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  slug: string;
  contactEmail?: string | null;
  contactPhone?: string | null;
  billingAddress?: {
    address?: string | null;
    city?: string | null;
    postalCode?: string | null;
    country?: string | null;
  };
  status: 'active' | 'inactive';
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Site auquel ce contenu est rattaché.
   */
  site?: (number | null) | Site;
  title: string;
  /**
   * Définie par le modèle — non modifiable.
   */
  slug: string;
  eyebrow?: string | null;
  excerpt?: string | null;
  heroImage?: (number | null) | Media;
  /**
   * Définie par le modèle.
   */
  isHomepage?: boolean | null;
  status: 'draft' | 'published' | 'archived';
  /**
   * Réservé à l’équipe technique.
   */
  layout?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seo?: {
    title?: string | null;
    description?: string | null;
    noIndex?: boolean | null;
  };
  sourceTemplatePageId?: string | null;
  contentScope?: ('global' | 'template' | 'site') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  /**
   * Site auquel ce contenu est rattaché.
   */
  site?: (number | null) | Site;
  title: string;
  /**
   * Ex. melodie-des-jardins-s
   */
  slug: string;
  category?: ('bouquets' | 'mariage' | 'naissance' | 'amour' | 'deuil' | 'cadeaux') | null;
  badge?: string | null;
  deliveryLabel?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  shortDescription?: string | null;
  composition?: string | null;
  deliveryDetails?: string | null;
  reference?: string | null;
  sku?: string | null;
  deliveryFeeFrom?: number | null;
  gallery?:
    | {
        imageUrl: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Ex. S, M, L avec un prix chacun.
   */
  variants?:
    | {
        label: string;
        code?: string | null;
        price: number;
        id?: string | null;
      }[]
    | null;
  addOns?:
    | {
        title: string;
        price: number;
        id?: string | null;
      }[]
    | null;
  image?: (number | null) | Media;
  /**
   * Si vous n'utilisez pas encore la médiathèque.
   */
  imageUrl?: string | null;
  price?: {
    from?: number | null;
    to?: number | null;
    currency?: string | null;
    onRequest?: boolean | null;
  };
  featured?: boolean | null;
  order?: number | null;
  status: 'draft' | 'published' | 'archived';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  /**
   * Site auquel ce contenu est rattaché.
   */
  site?: (number | null) | Site;
  status: 'pending' | 'confirmed' | 'cancelled' | 'completed';
  customerName: string;
  customerEmail: string;
  customerPhone?: string | null;
  eventDate?: string | null;
  eventType?: ('delivery' | 'wedding' | 'funeral' | 'other') | null;
  message: string;
  budget?: number | null;
  deliveryAddress?: string | null;
  deliverySlot?: ('morning' | 'afternoon' | 'evening') | null;
  paymentMethod?: ('on-delivery' | 'online-link') | null;
  orderTotal?: number | null;
  orderItems?:
    | {
        serviceId?: string | null;
        title?: string | null;
        quantity?: number | null;
        unitPrice?: number | null;
        lineTotal?: number | null;
        id?: string | null;
      }[]
    | null;
  sourcePage?: string | null;
  submittedAt?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'internal-manager' | 'client' | 'editor' | 'viewer';
  clients?: (number | Client)[] | null;
  sites?: (number | Site)[] | null;
  firstName?: string | null;
  lastName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'templates';
        value: number | Template;
      } | null)
    | ({
        relationTo: 'sectors';
        value: number | Sector;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  name?: T;
  template?: T;
  slug?: T;
  status?: T;
  client?: T;
  sector?: T;
  sitePages?: T;
  siteServices?: T;
  siteBookings?: T;
  logo?: T;
  favicon?: T;
  theme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        fontHeading?: T;
        fontBody?: T;
        borderRadius?: T;
      };
  contact?:
    | T
    | {
        phone?: T;
        email?: T;
        address?: T;
        hours?: T;
      };
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  domain?: T;
  subdomain?: T;
  useCustomDomain?: T;
  seo?:
    | T
    | {
        defaultTitle?: T;
        description?: T;
        ogImage?: T;
      };
  publishedAt?: T;
  clonedFromTemplateAt?: T;
  templateVersion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  eyebrow?: T;
  excerpt?: T;
  heroImage?: T;
  isHomepage?: T;
  status?: T;
  layout?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noIndex?: T;
      };
  sourceTemplatePageId?: T;
  contentScope?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  site?: T;
  title?: T;
  slug?: T;
  category?: T;
  badge?: T;
  deliveryLabel?: T;
  description?: T;
  shortDescription?: T;
  composition?: T;
  deliveryDetails?: T;
  reference?: T;
  sku?: T;
  deliveryFeeFrom?: T;
  gallery?:
    | T
    | {
        imageUrl?: T;
        id?: T;
      };
  variants?:
    | T
    | {
        label?: T;
        code?: T;
        price?: T;
        id?: T;
      };
  addOns?:
    | T
    | {
        title?: T;
        price?: T;
        id?: T;
      };
  image?: T;
  imageUrl?: T;
  price?:
    | T
    | {
        from?: T;
        to?: T;
        currency?: T;
        onRequest?: T;
      };
  featured?: T;
  order?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  site?: T;
  status?: T;
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  eventDate?: T;
  eventType?: T;
  message?: T;
  budget?: T;
  deliveryAddress?: T;
  deliverySlot?: T;
  paymentMethod?: T;
  orderTotal?: T;
  orderItems?:
    | T
    | {
        serviceId?: T;
        title?: T;
        quantity?: T;
        unitPrice?: T;
        lineTotal?: T;
        id?: T;
      };
  sourcePage?: T;
  submittedAt?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  scope?: T;
  site?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  contactEmail?: T;
  contactPhone?: T;
  billingAddress?:
    | T
    | {
        address?: T;
        city?: T;
        postalCode?: T;
        country?: T;
      };
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  sector?: T;
  description?: T;
  previewImage?: T;
  defaultTheme?:
    | T
    | {
        primaryColor?: T;
        secondaryColor?: T;
        accentColor?: T;
        fontHeading?: T;
        fontBody?: T;
        borderRadius?: T;
      };
  defaultPages?:
    | T
    | {
        title?: T;
        slug?: T;
        eyebrow?: T;
        excerpt?: T;
        isHomepage?: T;
        blocksJson?: T;
        seo?:
          | T
          | {
              title?: T;
              description?: T;
            };
        id?: T;
      };
  defaultServices?:
    | T
    | {
        title?: T;
        slug?: T;
        category?: T;
        badge?: T;
        deliveryLabel?: T;
        shortDescription?: T;
        imageUrl?: T;
        featured?: T;
        order?: T;
        price?:
          | T
          | {
              from?: T;
              currency?: T;
              onRequest?: T;
            };
        id?: T;
      };
  defaultBlocks?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sectors_select".
 */
export interface SectorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  clients?: T;
  sites?: T;
  firstName?: T;
  lastName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}